project:
  type: website
  output-dir: "docs"
format:
  html:
    theme: www/web_report.scss
    toc-title: Contents
    toc: true
    toc-depth: 3
    toc-location: right
    anchor-sections: false
    code-summary: "Reveal Code"
    code-copy: hover
    code-fold: true
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    code-block-bg: true
    code-block-border-left: "#008097"
    fig-width: 9
    fig-height: 7
    fig-dpi: 300
    warning: FALSE
    error: TRUE
    echo: FALSE
    message: FALSE
website:
  search:
    location: navbar
    type: textbox
  favicon: www/images/CPAL_favicon.ico
#  description: Description of this web report.
#  site-url:
#  repo-url:
#  google-analytics:
#  cookie consent: implied
  navbar:
      pinned: TRUE
      search: TRUE
      logo: www/images/CPAL_Logo_White.png
      logo-href: "https://github.com/childpovertyactionlab"
      collapse: false
      right:
        - text: "<b>Menu<b>"
          menu:
            - icon: buildings-fill
              text: "Citywide"
              href: index.html
            - icon: people-fill
              text: "Collaborators"
              href: collaborators.html
            - icon: pin-map-fill
              text: "Southwest Division"
              href: southwestpage.html 
            - icon: pin-map-fill
              text: "Northwest Division"
              href: northwestpage.html 
            - icon: pin-map-fill
              text: "Northeast Division"
              href: northeastpage.html 
            - icon: pin-map-fill
              text: "North Central Division"
              href: northcentralpage.html 
            - icon: pin-map-fill
              text: "Southeast Division"
              href: southeastpage.html     
            - icon: pin-map-fill
              text: "South Central Division"
              href: southcentralpage.html     
            - icon: github
              text: "Github"
              href: "https://github.com/childpovertyactionlab/"
  page-footer:
    center: Copyright 2024 <b>[The Child Poverty Action Lab](https://childpovertyactionlab.org/).</b>
    background: "#042d33"